### ISSUE TITLE
DSFA

### ISSUE THREAD

**Issue by kuehnef** [Fuenfgeld/DMA2022TeamA#15]
siehe Google docs. Ich habe bereits ein Dokument angelegt

**Comment by med4fox** [comment]
Hi @kuehnef,
magst du die DSFA mal in Github hochladen? Dann kann ich sie im Wiki verlinken.

Danke!

**Comment by kuehnef** [comment]
DIe DSFA habe ich hochgeladen. Über den Datenmanagmentplan müssten wir nochmal reden.

**Comment by kuehnef** [comment]
Soll ich im Wiki die DSFA in Word trotzdem verlinken ? Finde es in diesem Format eigentlich besser
