### ISSUE TITLE
Aufräumen Codebook

### ISSUE THREAD

**Issue by kuehnef** [Fuenfgeld/DMA2022TeamA#19]
Ich habe mal angefangen Ordner im Codebook zu erstellen, sodass es ein bisschen übersichtlicher wird. Bitte nicht wundern- man kann diese nur erstellen, wenn mindestens eine Datei darin ist- ich habe jeweils eine Datei "Test" erstellt, die wir später wieder löschen können. Die Bilder habe ich schon umsortiert. Bei den Collabbooks traue ich mich gerade nicht, da ich nicht weiß, wo diese wie verlinkt sind. NIcht, dass dann aufeinmal nix mehr funktioniert.

**Comment by Niklasprenissl** [comment]
Hi,
jetzt ist alles soweit aufgeräumt. Nur die DSFA bekomme ich nicht in den entsprechenden Ordner verschoben. Kannst du die vllt einfach in den richtigen Ordner hochladen und dann im Hauptordner löschen @kuehnef ?

**Comment by kuehnef** [comment]
Hi, mache ich. überarbeite es eh gerade.

**Comment by kuehnef** [comment]
jetzt müsste alles soweit aufgeräumt sein
