### ISSUE TITLE
Datenauswertung

### ISSUE THREAD

**Issue by kuehnef** [Fuenfgeld/DMA2022TeamA#8]

**Comment by kuehnef** [comment]
Ich scheitere an folgendem LEFTJOIN. Angeblich gibt es keine Tabelle dimConditions?

df = pd.read_sql_query("""
select dimEncounters.id, dimEncounters.start, dimEncounters.stop, dimEncounters.encounterclass, dimEncounters.code, dimEncounters.description  from dimEncounters
left JOIN
(select dimConditions.patient_id, dimConditions.encounter_id, dimConditions.code, dimConditions.description from dimConditions) 
on  dimEncounters.id = dimConditions.encounter_id
;""", dwh_conn
  )

**Comment by Niklasprenissl** [comment]
Hm, der Join wie du ihn willst wäre glaube ich:

df = pd.read_sql_query("""
select dimEncounters.id, dimEncounters.start, dimEncounters.stop, dimEncounters.encounterclass, dimEncounters.code, dimEncounters.description,dimConditions.patient_id, dimConditions.encounter_id, dimConditions.code, dimConditions.description from dimEncounters
left JOIN dimConditions
on dimEncounters.id = dimConditions.encounter_id
;""", dwh_conn
)

Andersrum ist aber glaube ich sinnvoller, oder? Sprich
df = pd.read_sql_query("""
select dimEncounters.id as ENCOUNTER_ID, dimEncounters.start, dimEncounters.stop, dimEncounters.encounterclass, dimEncounters.code, dimEncounters.description,dimConditions.patient_id, dimConditions.code, dimConditions.description from dimConditions
left JOIN dimEncounters
on dimEncounters.id = dimConditions.encounter_id 
;""", dwh_conn
)

**Comment by med4fox** [comment]
Hallo,
ich habe ein Problem die Anzahl der pro Jahr durchgeführten Proceduren graphisch darzustellen.
Fragestellung: Hat sich durch Corona die Anzahl der durchgeführten Proceduren geändert?

Ziel: Berechnung der Anzahl der insgesamt durchgeführten Proceduren und Aufschlüsselung nach Art der durchgeführten Procedur pro Jahr

Das hat bisher funktioniert:- extrahieren der relevanten Daten aus unserem Datawarehouse- Durchführung einer einfach Datenexploration

Mein Problem: Ich schaffe es nicht die Daten nach dem Jahr aufzuschlüsseln.
Meine erste Überlegung wäre es im df_procedures erstmal nur nach dem Jahr aufzuschlüsseln:

df_procedures = datetime.strftime("DATE", "%Y")

allerdings stoße ich immer auf folgende Fehlermeldung:
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'str'

Hat hier jemand einen Lösungsvorschlag?

**Comment by Niklasprenissl** [comment]
Hey,

hm guck mal in das Prediction.ipynb rein, da habe ich an einer Stelle auch das Datumsformat geändert.

dffinal["DATE"] = pd.to_datetime(dffinal["DATE"])
dffinal["DATE"] = dffinal["DATE"].dt.to_period("Y")

Wenn du da anstatt von dffinal den Namen von deinem Dataframe einträgst müsste das eigentlich klappen.

LG

**Comment by med4fox** [comment]
Perfekt, danke!
